version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: guesthouse-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: guesthouse
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - guesthouse-network

  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: guesthouse-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/guesthouse?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - CLIENT_URL=http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - guesthouse-network

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: guesthouse-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - guesthouse-network

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: guesthouse-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - guesthouse-network

volumes:
  mongodb_data:

networks:
  guesthouse-network:
    driver: bridge 